### ISSUE TITLE
DCC throws value error?

### ISSUE THREAD

**Issue by mathavanpu** [dieterich-lab/DCC#103]
hi, 
I have executed the DCC, the circular RNA counts and co-ordinates files are generated. For finding the CircSkipJunction I got the error mentioned below. Can you please guide me resolve this

Traceback (most recent call last):
  File "/home/mathavan/.local/bin/DCC", line 33, in <module>
    sys.exit(load_entry_point('DCC==0.5.0', 'console_scripts', 'DCC')())
  File "/home/mathavan/.local/lib/python3.10/site-packages/DCC-0.5.0-py3.10.egg/DCC/main.py", line 490, in main
  File "/home/mathavan/.local/lib/python3.10/site-packages/DCC-0.5.0-py3.10.egg/DCC/main.py", line 679, in findCircSkipJunction
  File "/home/mathavan/.local/lib/python3.10/site-packages/DCC-0.5.0-py3.10.egg/DCC/Circ_nonCirc_Exon_Match.py", line 281, in findcircAdjacent
  File "/home/mathavan/.local/lib/python3.10/site-packages/DCC-0.5.0-py3.10.egg/DCC/Circ_nonCirc_Exon_Match.py", line 222, in getAdjacent
ValueError: invalid literal for int() with base 10: '8"'

**Comment by tjakobi** [comment]
Hi @mathavanpu,

This error seems to have been caused by an update to HTSeq. I've corrected the code in DCC to correctly work with newer HTSeq versions.

Please reinstall from GitHub and see if the error is fixed for you.

Tobias

**Comment by jaanckae** [comment]
Hi @tjakobi 

I'm having the same issue as mentioned above:


Count CircSkip junctions
Traceback (most recent call last):
  File "/usr/local/bin/circtools", line 18, in <module>
    import circtools
  File "/usr/local/lib/python3.9/dist-packages/circtools/__init__.py", line 2, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/circtools/circtools.py", line 31, in main
    CircTools()
  File "/usr/local/lib/python3.9/dist-packages/circtools/circtools.py", line 77, in __init__
    getattr(self, args.command)()
  File "/usr/local/lib/python3.9/dist-packages/circtools/circtools.py", line 609, in detect
    DCC.main(parser)
  File "/usr/local/lib/python3.9/dist-packages/DCC/main.py", line 490, in main
    CircSkipfiles = findCircSkipJunction(output_coordinates, options.tmp_dir,
  File "/usr/local/lib/python3.9/dist-packages/DCC/main.py", line 679, in findCircSkipJunction
    circStartAdjacentExons, circStartAdjacentExonsIv = CCEM.findcircAdjacent(circStartExons, Custom_exon_id2Iv,
  File "/usr/local/lib/python3.9/dist-packages/DCC/Circ_nonCirc_Exon_Match.py", line 281, in findcircAdjacent
    interval = Custom_exon_id2Iv[self.getAdjacent(ids, start=start)]
  File "/usr/local/lib/python3.9/dist-packages/DCC/Circ_nonCirc_Exon_Match.py", line 222, in getAdjacent
    exon_number = int(custom_exon_id.split(':')[1]) - 1
ValueError: invalid literal for int() with base 10: '2"'

It indeed seems that the HTSeq module is adding unwanted quotes to the modified GTF file.
Is it possible to add this fix to the PyPi installation files?

Thanks
Jasper

**Comment by tjakobi** [comment]
Hi @jaanckae,

Thank you for your report.

Are you using the master branch or a released PyPi version?

I did not yet publish a new DCC release yet, but will do so soon. 

Could you please give the master branch version a try?

Thank you!

**Comment by jaanckae** [comment]
Hi @tjakobi 

Master branch works perfect, thank you. 
On to the next part of the program.

**Comment by kelly-sovacool** [comment]
@tjakobi do you plan to release a new version with this bug fix?

**Comment by tjakobi** [comment]
Hi @kelly-sovacool,

DCC is now part of circtools at https://github.com/jakobilab/circtools and this repository is not updated anymore. 

The issues has been fixed in circtools which is available via `pip` or from GitHub.

Best,

Tobias

**Comment by kelly-sovacool** [comment]
Great, thanks for letting us know about the new repo
