### ISSUE TITLE
stop at  Using files _tmp_DCC/tmp_circCount and _tmp_DCC/tmp_coordinates for filtering

### ISSUE THREAD

**Issue by ChrisLou-bioinfo** [dieterich-lab/DCC#52]
2018-07-02 04:22:50,597 Combining individual circRNA read counts
2018-07-02 19:54:58,365 Swapping strand information
2018-07-02 19:56:08,607 Write in annotation
2018-07-02 19:56:08,607 Select gene features in Annotation file
2018-07-02 20:17:05,993 Filtering started
2018-07-02 20:17:05,993 Using files _tmp_DCC/tmp_circCount and _tmp_DCC/tmp_coordinates for filtering

process stop at 2018-07-02 20:17:05,993 Using files _tmp_DCC/tmp_circCount and _tmp_DCC/tmp_coordinates for filtering

run commend：
DCC @samplesheet -mt1 @mate1 -mt2 @mate2 -D -R /home/dell/refer/hg38_DCC_Repeats.gtf -an /home/dell/refer/gencode.v28.primary_assembly.annotation.gtf -Pi -ss -L 20 -F -M -Nr 1 2 -fg -T 20

the monitor  had showed nothing about DCC program

thanks

**Comment by tjakobi** [comment]
Dear @ChrisLou-bioinfo ,

does DCC exit with an error message (a Python error or similar on the console) or with a clean status 0? You may want to run DCC again with the ``-k`` flag in order to keep temporary files that may be helpful for debugging.

Cheers,
Tobias

**Comment by ChrisLou-bioinfo** [comment]
Hi,Tobias
Thanks for your reply
There are some warnings about memory-error

Using files _tmp_DCC/tmp_circCount and _tmp_DCC/tmp_coordinates for filtering
Traceback (most recent call last):
  File "/home/dell/.local/bin/DCC", line 11, in <module>
    load_entry_point('DCC==0.4.6', 'console_scripts', 'DCC')()
  File "build/bdist.linux-x86_64/egg/DCC/main.py", line 339, in main
  File "build/bdist.linux-x86_64/egg/DCC/circFilter.py", line 60, in readcirc
MemoryError

My Server Memory is 64GB
Sample Number is 168

thanks

Chris

**Comment by tjakobi** [comment]
Dear @ChrisLou-bioinfo,

thank you for your feedback. I never ran DCC with so many samples, it may actually be a memory issue. I will see if I can reduce the memory usage in this part of the code.

Cheers,
Tobias

**Comment by ChrisLou-bioinfo** [comment]
Thanks!
Waiting for your software updated
