### ISSUE TITLE
DCC installation error

### ISSUE THREAD

**Issue by giuseppe0525** [dieterich-lab/DCC#56]
I got an error when trying to install DCC-0.4.6.

I followed the guide to install the software:

```
Download the latest stable DCC release
$ tar -xvf DCC-<version>.tar.gz

$ cd DCC-<version>

$ python setup.py install --user
```

I received the following error message when I run the install command:

```
[root@localhost DCC-0.4.6]# python setup.py install --user
running install
running bdist_egg
running egg_info
creating DCC.egg-info
writing DCC.egg-info/PKG-INFO
writing dependency_links to DCC.egg-info/dependency_links.txt
writing entry points to DCC.egg-info/entry_points.txt
writing requirements to DCC.egg-info/requires.txt
writing top-level names to DCC.egg-info/top_level.txt
writing manifest file 'DCC.egg-info/SOURCES.txt'
reading manifest file 'DCC.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 4: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

warning: no files found matching 'data/chimeric_junctions'
warning: no files found matching 'data/mate1'
warning: no files found matching 'data/mate2'
writing manifest file 'DCC.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/DCC
copying DCC/Circ_nonCirc_Exon_Match.py -> build/lib/DCC
copying DCC/CombineCounts.py -> build/lib/DCC
copying DCC/IntervalTree.py -> build/lib/DCC
copying DCC/__init__.py -> build/lib/DCC
copying DCC/circAnnotate.py -> build/lib/DCC
copying DCC/circFilter.py -> build/lib/DCC
copying DCC/findcircRNA.py -> build/lib/DCC
copying DCC/fix2chimera.py -> build/lib/DCC
copying DCC/genecount.py -> build/lib/DCC
copying DCC/main.py -> build/lib/DCC
creating build/lib/DCC/data
copying DCC/data/DCC.Repeats -> build/lib/DCC/data
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/DCC
copying build/lib/DCC/Circ_nonCirc_Exon_Match.py -> build/bdist.linux-x86_64/egg/DCC
copying build/lib/DCC/CombineCounts.py -> build/bdist.linux-x86_64/egg/DCC
copying build/lib/DCC/IntervalTree.py -> build/bdist.linux-x86_64/egg/DCC
copying build/lib/DCC/__init__.py -> build/bdist.linux-x86_64/egg/DCC
copying build/lib/DCC/circAnnotate.py -> build/bdist.linux-x86_64/egg/DCC
copying build/lib/DCC/circFilter.py -> build/bdist.linux-x86_64/egg/DCC
copying build/lib/DCC/findcircRNA.py -> build/bdist.linux-x86_64/egg/DCC
copying build/lib/DCC/fix2chimera.py -> build/bdist.linux-x86_64/egg/DCC
copying build/lib/DCC/genecount.py -> build/bdist.linux-x86_64/egg/DCC
copying build/lib/DCC/main.py -> build/bdist.linux-x86_64/egg/DCC
creating build/bdist.linux-x86_64/egg/DCC/data
copying build/lib/DCC/data/DCC.Repeats -> build/bdist.linux-x86_64/egg/DCC/data
byte-compiling build/bdist.linux-x86_64/egg/DCC/Circ_nonCirc_Exon_Match.py to Circ_nonCirc_Exon_Match.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/DCC/Circ_nonCirc_Exon_Match.py", line 197
    print lin.strip('\n')
            ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/DCC/CombineCounts.py to CombineCounts.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/DCC/IntervalTree.py to IntervalTree.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/DCC/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/DCC/circAnnotate.py to circAnnotate.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/DCC/circFilter.py to circFilter.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/DCC/circFilter.py", line 66
    print 'Filtering by read counts'
                                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'Filtering by read counts')?

byte-compiling build/bdist.linux-x86_64/egg/DCC/findcircRNA.py to findcircRNA.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/DCC/findcircRNA.py", line 79
    print 'Read %s has more than 2 count.' % read
                                         ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'Read %s has more than 2 count.' % read)?

byte-compiling build/bdist.linux-x86_64/egg/DCC/fix2chimera.py to fix2chimera.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/DCC/genecount.py to genecount.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/DCC/genecount.py", line 118
    print "\t=> gathering read counts for start positions [%s]" % bamfile
                                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "\t=> gathering read counts for start positions [%s]" % bamfile)?

byte-compiling build/bdist.linux-x86_64/egg/DCC/main.py to main.cpython-36.pyc
  File "build/bdist.linux-x86_64/egg/DCC/main.py", line 115
    print "Could not create output folder %s" % options.out_dir
                                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Could not create output folder %s" % options.out_dir)?

creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.6
copying and adjusting scripts/DCC -> build/scripts-3.6
changing mode of build/scripts-3.6/DCC from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.6/DCC -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/DCC to 755
copying DCC.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DCC.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DCC.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DCC.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DCC.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying DCC.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/DCC-0.4.6-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing DCC-0.4.6-py3.6.egg
Removing /root/.local/lib/python3.6/site-packages/DCC-0.4.6-py3.6.egg
Copying DCC-0.4.6-py3.6.egg to /root/.local/lib/python3.6/site-packages
DCC 0.4.6 is already the active version in easy-install.pth
Installing DCC script to /root/.local/bin
Installing DCC script to /root/.local/bin

Installed /root/.local/lib/python3.6/site-packages/DCC-0.4.6-py3.6.egg
Processing dependencies for DCC==0.4.6
Searching for pandas==0.23.4
Best match: pandas 0.23.4
Adding pandas 0.23.4 to easy-install.pth file

Using /usr/local/bin/anaconda3/lib/python3.6/site-packages
Searching for numpy==1.14.5
Best match: numpy 1.14.5
Adding numpy 1.14.5 to easy-install.pth file

Using /usr/local/bin/anaconda3/lib/python3.6/site-packages
Searching for pysam==0.13
Best match: pysam 0.13
Adding pysam 0.13 to easy-install.pth file

Using /usr/local/bin/anaconda3/lib/python3.6/site-packages
Searching for HTSeq==0.10.0
Best match: HTSeq 0.10.0
Adding HTSeq 0.10.0 to easy-install.pth file

Using /usr/local/bin/anaconda3/lib/python3.6/site-packages
Searching for pytz==2017.3
Best match: pytz 2017.3
Adding pytz 2017.3 to easy-install.pth file

Using /usr/local/bin/anaconda3/lib/python3.6/site-packages
Searching for python-dateutil==2.6.1
Best match: python-dateutil 2.6.1
Adding python-dateutil 2.6.1 to easy-install.pth file

Using /usr/local/bin/anaconda3/lib/python3.6/site-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /usr/local/bin/anaconda3/lib/python3.6/site-packages
Finished processing dependencies for DCC==0.4.6


[root@localhost DCC-0.4.6]# DCC --version
Traceback (most recent call last):
  File "/usr/local/bin/anaconda3/bin/DCC", line 11, in <module>
    load_entry_point('DCC==0.4.6', 'console_scripts', 'DCC')()
  File "/usr/local/bin/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/bin/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/bin/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/bin/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/.local/lib/python3.6/site-packages/DCC-0.4.6-py3.6.egg/DCC/__init__.py", line 2, in <module>
ModuleNotFoundError: No module named 'findcircRNA'
```
The desktop and the version of DCC associated packages are listed as followed:

OS CentOS Linux release 7.5.1804 (Core)
Python Python 3.6.3 :: Anaconda custom (64-bit)
DCC 0.4.6
HTSeq 0.10.0
pysam 0.13.0
pandas 0.23.4
numpy 1.14.5

Any help would be truly appreciated!

**Comment by tjakobi** [comment]
DCC requires Python version 2.7 and you are trying to install it using Python3.
Unfortunately, right now we cannot provide a Python3-only version.
Please install Python2 (if not already installed) and call the install script with `python2 setup.py`.

**Comment by giuseppe0525** [comment]
Thank you. It fixed the problem.
