### ISSUE TITLE
 Filtering by read counts

### ISSUE THREAD

**Issue by JunmingH** [dieterich-lab/DCC#74]
**Describe the bug**
Hi I am trying to run DCC but stock at filtering part
the log file is:

2019-12-12 15:38:13,799 Using files _tmp_DCC/tmp_circCount and _tmp_DCC/tmp_coordinates for filtering
2019-12-12 17:00:57,987 Filtering by read counts

Traceback (most recent call last):
  File "/restricted/projectnb/casa/jmh/RNA-seq/circu_RNA/DCC-0.4.7/DCC/main.py", line 818, in <module>
    main()
  File "/restricted/projectnb/casa/jmh/RNA-seq/circu_RNA/DCC-0.4.7/DCC/main.py", line 348, in main
    count0, indx0 = filt.filtercount(count, indx)  # result of first filtering by read counts
  File "/restricted/projectnb/casa/jmh/RNA-seq/circu_RNA/DCC-0.4.7/DCC/circFilter.py", line 74, in filtercount
    if sum(count[itm] >= self.countthreshold) >= self.replicatethreshold:
TypeError: 'bool' object is not iterable

Could you please give me some idea about this issue？
Many thanks!

**Comment by tjakobi** [comment]
Dear @JunmingH,

do you have he complete command line call for this error? It seems that wrong values have been specified which is not correctly caught by the code.

Cheers,
Tobias
