### ISSUE TITLE
Cannot setup in computer

### ISSUE THREAD

**Issue by Golden-proteogenomics** [dieterich-lab/DCC#92]
hello,
     I use the last release software(DCC--0.5.0) and used the following command which comes from the readme file to install it, however, that cannot be installed on my computer with Linux operation. the detail of command and error was listed.
"$ tar -xvf DCC-<version>.tar.gz

$ cd DCC-DCC-0.5.0

$ python3 setup.py install"
$ DCC --version
DCC: command not found

**Comment by chungtseng** [comment]
Same issue with me! 
$ DCC --version
DCC: command not found

$ python scripts/DCC --version
Traceback (most recent call last):
  File "scripts/DCC", line 3, in <module>
    import DCC.main
  File "/home/user/.local/lib/python3.6/site-packages/DCC-0.4.7-py3.6.egg/DCC/__init__.py", line 2, in <module>
ModuleNotFoundError: No module named 'findcircRNA'

$ python DCC/main.py --version
Traceback (most recent call last):
  File "DCC/main.py", line 16, in <module>
    from . import CombineCounts as Cc
ImportError: cannot import name 'CombineCounts'
